name: GitHub Classroom Workflow

on: workflow_dispatch

env:
  COPY-ISSUES: "true"
  GRADING: "true"
  MOODLE: "true"
  WORKFLOWS: BZZ-Commons/workflows
  SOURCE_REPO: BZZ-Commons/copy-issues

permissions:
  checks: write
  actions: read
  contents: read

jobs:
  setup:
    if: ${{ contains(github.actor, 'classroom') }}
    uses: BZZ-Commons/workflows/.github/workflows/setup.yml@main
    with:
      sourc_repo: ${{ env.SOURCE_REPO }}

  grading:
    if: ${{ !contains(github.actor, 'classroom') }}
    uses: BZZ-Commons/workflows/.github/workflows/setup.yml@main

